> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy Library


### Numerical operations on arrays using Numpy function

Write a short introduction about Numpy and list the chosen functions. 

Numpy library provides various built-in functions to perform various numerical operations on arrays which makes our tasks
easier.
    
    first import numpy as np
    
- function 1 - np.array() - This function creates a numpy array.
- function 2 - np.dot() - This function return the dot product of two arrays.
- function 3 - np.matmul() - This function returns the matrix multiplication of two vectors.
- function 4 - np.concatenate() - This function concatenates or joins two vectors.
- function 5 - np.ones() - This function fills all elements with 1 of matrix according to user defined dimensions.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [3]:
!pip install jovian --upgrade -q

In [4]:
import jovian

In [5]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rohanj0306/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/rohanj0306/numpy-array-operations


'https://jovian.ai/rohanj0306/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [6]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.ones # (change this)
function2 = np.array
function3 = np.dot
function4 = np.matmul
function5 = np.random.rand

## Function 1 - np.matmul

This function returns the matrix multiplication of two vectors.

In [10]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.matmul(arr1,arr2)

array([[21., 24., 27.],
       [47., 54., 61.]])

np.matmul(arr1,arr2) this function perfroms matrix multiplication of arr1 and arr2 and returns multiplied matrix.

In [13]:
# Example 2 - working
arr4 = np.array([[1,5,2],[4,2,7]])
arr5 = np.array([[6,3],[2,6],[6,3]])
np.matmul(arr4,arr5)

array([[28, 39],
       [70, 45]])

size of arr4 is (2,3) and size of arr5 is (3,2) so matrix multiplaication is possible and perfroms matrix mul and returns multiplied matrix.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [5, 4],
        [7, 2]]

np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Explanation about example (why it breaks and how to fix it)

As the column dimension of arr1 is different from row dimension of arr2 matrix multiplication is not possible. so compiler returns a ValueError.

how to fix it - we have to input two matrices such that the column dimension of first matrix matches with row dimension of second matrix.

Some closing comments about when to use this function.

this function becomes very handy when we want to perform multiplication of two matrices easily.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rohanj0306/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/rohanj0306/numpy-array-operations


'https://jovian.ai/rohanj0306/numpy-array-operations'

## Function 2 - np.dot

This function return the dot product of two arrays.

In [19]:
# Example 1 - working
arr3 =np.array([1,3,5])
arr4 =np.array([6,3,1])
np.dot(arr3,arr4)

20

In the above example arr3 and arr4 are created using np.array function and dot product of both the arrays are performed using np.dot function which multiplies corresponding elements of two arrays and sums them and returns the answer.

In [24]:
# Example 2 - working
arr6 = np.array([4,1,2])
arr7 =np.array([24,1,5])
np.dot(arr6,arr7)

107

In the above example arr3 and arr4 are created using np.array function and dot product of both the arrays are performed using np.dot function which multiplies corresponding elements of two arrays and sums them and returns the answer.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
arr6 =np.array([4,1,14])
arr7 =np.array([[4,1,1],
               [2,1,3]])
np.dot(arr6,arr7)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

As the column dimension of arr6 is different from row dimension of arr7 dot product is not possible. so compiler returns a ValueError.

how to fix it - we have to input two arrays such that the column dimension of first array matches with row dimension of second array.

Some closing comments about when to use this function.

This function is pretty useful when we to do linear multiplication and sum all the products.
This function helps programmer save time and reduce task of programmer to write function for dot product of two arrays.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rohanj0306/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/rohanj0306/numpy-array-operations


'https://jovian.ai/rohanj0306/numpy-array-operations'

## Function 3 - np.concatenate

This function concatenates or joins two vectors.

In [38]:
# Example 1 - working
arr8=np.array([[5,2,1,4,51,5],[4,1,4,5,1,5]])
arr9=np.array([15,15,14,14,41,5])
res_arr=np.concatenate((arr8,arr9.reshape(1,6)),axis=0)
res_arr

array([[ 5,  2,  1,  4, 51,  5],
       [ 4,  1,  4,  5,  1,  5],
       [15, 15, 14, 14, 41,  5]])

In the above example two arrays arr8 and arr9 are concatenated using np.concatenate function. arr9.reshape function inside concatenate function reshapes the dimensions of arr9 into (1,6) and axis = 0 says the arr9 is to be concatenated row axis in an arr8.

In [46]:
# Example 2 - working
array1=np.array([[1,2,3,4,5],
                 [5,6,3,1,4],
                 [4,1,4,5,3]])
array2 = np.array([[11],
                   [22],
                   [33],
                   [44],
                   [55],
                   [66],
                   [77],
                   [88],
                   [99],
                   [10],
                   [11],
                   [12],
                   [13],
                   [14],
                   [15],])
res_array=np.concatenate((array1,array2.reshape(3,5)),axis=1)
res_array

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55],
       [ 5,  6,  3,  1,  4, 66, 77, 88, 99, 10],
       [ 4,  1,  4,  5,  3, 11, 12, 13, 14, 15]])

In the above example two arrays array1 and array2 are concatenated using np.concatenate function. array2.reshape function inside concatenate function reshapes the dimensions of array2 into (3,5) from (15,1) and concatenates to array1 and axis = 1 says the array2 is to be concatenated with column axis of array1.

In [65]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7, 8]])
np.concatenate((a, b), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

The ValueError is occured as the dimnesions of two arrays a and b are different and cannot be concatenated.

fix - reshape function can be used to reshape the dimnesions of array b and then concatenate.

This function is very handy when we want to concatenate two arrays .

In [2]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rohanj0306/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/rohanj0306/numpy-array-operations


'https://jovian.ai/rohanj0306/numpy-array-operations'

## Function 4 - np.ones

This function creates a matrix with all its elements equal to 1 of user specified size.

In [9]:
# Example 1 - working
a1 = np.zeros([3,3])
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

a1 matrix is created of size (3,3) with all its elements equal to 1.

In [11]:
# Example 2 - working
b1 = np.ones([4,4,4])
b1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

3d matrix is created of size (4,4,4) with all its elements equal to 1 and is assigned to variable b1.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
c1=np.ones([1,41.4,4])

TypeError: 'float' object cannot be interpreted as an integer

only integers are allowed while mentioning dimensions ,here float cannot be used as dimensions.

If programmer wants to create a matrix with all same elements in it , this function can be used.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rohanj0306/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/rohanj0306/numpy-array-operations


'https://jovian.ai/rohanj0306/numpy-array-operations'

## Function 5 - np.random.rand

This function creates a matrix of user specified size with random numbers in it.

In [17]:
# Example 1 - working
np.random.rand(5)

array([0.10361656, 0.93229558, 0.16011428, 0.41202989, 0.77586472])

An array of positive random elements are created of size (5)

In [18]:
# Example 2 - working
np.random.randn(2,2)

array([[ 0.44623062, -0.2255944 ],
       [ 0.87320445, -1.90055842]])

In the above example instead of rand randn is used which creates matrix with random variables which can include negative numbers also.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
np.random()

TypeError: 'module' object is not callable

Explanation about example (why it breaks and how to fix it)

In the above example compiler returns TypeError as rand module is not included in syntax .

either rand or randn module has to be included.

This function is useful when we want to create matrix of random numbers .

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rohanj0306/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/rohanj0306/numpy-array-operations


'https://jovian.ai/rohanj0306/numpy-array-operations'

## Conclusion

In this notebook we describe the uses of five interesting numpy function. To describe each function we provide three examples in which two of them are successfully running while one has a breakdown i.e. it wont run succesfully and shows some error. Each examples has their own description about their running process and uses as well as the reasons for not showing outputs.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>